"use client";

import React, { createContext, useContext, useEffect, useMemo, useState } from "react";

export type LangOption = { value: string; label: string; flag: string };

type Dictionary = Record<string, string>;

const OPTIONS: LangOption[] = [
  { value: "en", label: "English", flag: "🇬🇧" },
  { value: "ro", label: "Română", flag: "🇷🇴" },
  { value: "de", label: "Deutsch", flag: "🇩🇪" },
  { value: "fr", label: "Français", flag: "🇫🇷" },
  { value: "es", label: "Español", flag: "🇪🇸" },
  { value: "it", label: "Italiano", flag: "🇮🇹" },
  { value: "pt", label: "Português", flag: "🇵🇹" },
  { value: "nl", label: "Nederlands", flag: "🇳🇱" },
  { value: "pl", label: "Polski", flag: "🇵🇱" },
  { value: "tr", label: "Türkçe", flag: "🇹🇷" },
  { value: "uk", label: "Українська", flag: "🇺🇦" },
  { value: "ru", label: "Русский", flag: "🇷🇺" },
  { value: "ar", label: "العربية", flag: "🇸🇦" },
  { value: "zh-cn", label: "中文", flag: "🇨🇳" },
  { value: "ja", label: "日本語", flag: "🇯🇵" },
  { value: "ko", label: "한국어", flag: "🇰🇷" },
  { value: "hi", label: "हिन्दी", flag: "🇮🇳" },
  { value: "hu", label: "Magyar", flag: "🇭🇺" },
  { value: "cs", label: "Čeština", flag: "🇨🇿" },
  { value: "sv", label: "Svenska", flag: "🇸🇪" },
];

const en: Dictionary = {
  brandSubtitle: "Modern social platform",
  feed: "Feed",
  videos: "Videos",
  create: "Create",
  notifications: "Notifications",
  analytics: "Analytics",
  privacy: "Privacy",
  profile: "Profile",
  activity: "Activity",
  system: "System",
  allServicesOnline: "All services online",
  tips: "Tips",
  uiConsistency: "Use the UI kit components for consistency.",
  login: "Login",
  register: "Register",
  logout: "Logout",
  checkingSession: "Checking session...",
  loading: "Loading...",
  homeTitle: "Reelio",
  homeSubtitle: "Ultimate UI System enabled",
  online: "ONLINE",
  homeIntro: "Use Register/Login, then open Feed and Create a Post. API docs at /docs.",
  openFeed: "Open Feed",
  createPost: "Create Post",
  loginTitle: "Login",
  loginSubtitle: "Use a real account session with cookies and profile state.",
  email: "Email",
  password: "Password",
  createAccount: "Create account",
  registerSubtitle: "Register a Reelio user and start posting.",
  username: "Username",
  min8: "Minimum 8 characters",
  accountCreated: "Account created",
  nowLoggedIn: "You are now logged in.",
  feedHomeTitle: "Feed / Home",
  feedHomeSubtitle: "Browse public posts from Reelio creators.",
  noPostsYet: "No posts available yet.",
  videosTitle: "Feed / Videos",
  videosSubtitle: "Separate video grid for Reelio clips.",
  noVideosYet: "No videos available yet.",
  comments: "Comments",
  showComments: "Show comments",
  hideComments: "Hide comments",
  writeComment: "Write a comment...",
  postComment: "Post comment",
  shareThoughts: "Share your thoughts under this post.",
  logInToComment: "Log in to add comments.",
  loadingComments: "Loading comments...",
  noCommentsYet: "No comments yet.",
  reply: "Reply",
  edit: "Edit",
  delete: "Delete",
  save: "Save",
  cancel: "Cancel",
  translate: "Translation",
  showOriginal: "Show original",
  translating: "Translating...",
  translationUnavailable: "Translation unavailable",
  profileLoading: "Loading profile...",
  noBioYet: "No bio yet.",
  profileControls: "Profile, personal details, security, and account controls",
  posts: "Posts",
  personalData: "Personal data",
  account: "Account",
  myPosts: "My posts",
  allPostsByUser: "All posts created by this user.",
  personalDetails: "Personal details",
  chooseVisibility: "Choose what others can see on your profile.",
  displayName: "Display name",
  bio: "Bio",
  fromWhere: "Where are you from",
  whereWork: "Where do you work",
  studies: "Studies",
  activitiesLike: "Activities you like",
  publicAnyone: "Anyone",
  friendsOnly: "Friends only",
  onlyMe: "Only me",
  profilePicture: "Profile picture",
  avatarPreviewAdjust: "Avatar preview and adjustment",
  visibleCropLive: "The visible circular crop updates live.",
  focusX: "Focus X",
  focusY: "Focus Y",
  zoom: "Zoom",
  filter: "Filter",
  saveProfile: "Save profile",
  profileUpdated: "Profile updated",
  publicDetailsSaved: "Your public details were saved.",
  changeEmail: "Change email",
  newEmail: "New email",
  emailUpdated: "Email updated",
  changePassword: "Change password",
  currentPassword: "Current password",
  newPassword: "New password",
  passwordChanged: "Password changed",
  temporaryDeactivation: "Temporary deactivation",
  hideAccountTemporary: "Hide the account temporarily and sign out.",
  deactivateTemporarily: "Deactivate temporarily",
  language: "Language",
  followingFeedError: "Following feed error",
  privacyDashboard: "Privacy / Dashboard",
  createTitle: "Create",
  createSubtitle: "Publish text posts, attach an image or video from your PC, or open a new realm.",
  realm: "Realm",
  post: "Post",
  name: "Name",
  slug: "Slug",
  description: "Description",
  createRealm: "Create realm",
  postTo: "Post to",
  chooseWherePost: "Choose where the post should appear, for example Home or Videos.",
  title: "Title",
  captionDescription: "Caption / Description",
  imageOrVideoComputer: "Image or video from your computer",
  chooseAnyImageVideo: "You can choose any image or video file. The app will fit it inside the post without stretching it.",
  publishPost: "Publish post",
  notificationsTitle: "Notifications",
  analyticsTitle: "Analytics / Creator",
  translateThisText: "Translate this text",
  translatedFromOriginal: "Translated from original",
  startConversation: "Start the conversation",
};
const ro: Dictionary = {
  brandSubtitle: "Platformă socială modernă",
  feed: "Feed",
  videos: "Videoclipuri",
  create: "Creează",
  notifications: "Notificări",
  analytics: "Analitice",
  privacy: "Confidențialitate",
  profile: "Profil",
  activity: "Activitate",
  system: "Sistem",
  allServicesOnline: "Toate serviciile online",
  tips: "Sfaturi",
  uiConsistency: "Folosește componentele UI pentru consistență.",
  login: "Autentificare",
  register: "Înregistrare",
  logout: "Deconectare",
  checkingSession: "Se verifică sesiunea...",
  loading: "Se încarcă...",
  homeTitle: "Reelio",
  homeSubtitle: "Sistemul UI Ultimate este activ",
  online: "ONLINE",
  homeIntro: "Folosește Înregistrare/Autentificare, apoi deschide Feed și creează o postare. Documentația API este la /docs.",
  openFeed: "Deschide Feed",
  createPost: "Creează postare",
  loginTitle: "Autentificare",
  loginSubtitle: "Folosește o sesiune reală cu cookies și stare de profil.",
  email: "Email",
  password: "Parolă",
  createAccount: "Creează cont",
  registerSubtitle: "Înregistrează un utilizator Reelio și începe să postezi.",
  username: "Nume utilizator",
  min8: "Minimum 8 caractere",
  accountCreated: "Cont creat",
  nowLoggedIn: "Ești acum autentificat.",
  feedHomeTitle: "Feed / Acasă",
  feedHomeSubtitle: "Vezi postările publice ale creatorilor Reelio.",
  noPostsYet: "Nu există încă postări.",
  videosTitle: "Feed / Videoclipuri",
  videosSubtitle: "Grid separat pentru clipurile Reelio.",
  noVideosYet: "Nu există încă videoclipuri.",
  comments: "Comentarii",
  showComments: "Afișează comentariile",
  hideComments: "Ascunde comentariile",
  writeComment: "Scrie un comentariu...",
  postComment: "Publică comentariul",
  shareThoughts: "Spune-ți părerea la această postare.",
  logInToComment: "Autentifică-te pentru a comenta.",
  loadingComments: "Se încarcă comentariile...",
  noCommentsYet: "Nu există comentarii încă.",
  reply: "Răspunde",
  edit: "Editează",
  delete: "Șterge",
  save: "Salvează",
  cancel: "Anulează",
  translate: "Traducere",
  showOriginal: "Afișează originalul",
  translating: "Se traduce...",
  translationUnavailable: "Traducerea nu este disponibilă",
  profileLoading: "Se încarcă profilul...",
  noBioYet: "Niciun bio încă.",
  profileControls: "Profil, date personale, securitate și controlul contului",
  posts: "Postări",
  personalData: "Date personale",
  account: "Cont",
  myPosts: "Postările mele",
  allPostsByUser: "Toate postările create de acest utilizator.",
  personalDetails: "Detalii personale",
  chooseVisibility: "Alege ce pot vedea ceilalți pe profilul tău.",
  displayName: "Nume afișat",
  bio: "Bio",
  fromWhere: "De unde ești",
  whereWork: "Unde lucrezi",
  studies: "Studii",
  activitiesLike: "Activități care îți plac",
  publicAnyone: "Oricine",
  friendsOnly: "Doar prietenii",
  onlyMe: "Doar eu",
  profilePicture: "Poză de profil",
  avatarPreviewAdjust: "Previzualizare și ajustare avatar",
  visibleCropLive: "Decupajul circular vizibil se actualizează live.",
  focusX: "Focus X",
  focusY: "Focus Y",
  zoom: "Zoom",
  filter: "Filtru",
  saveProfile: "Salvează profilul",
  profileUpdated: "Profil actualizat",
  publicDetailsSaved: "Detaliile tale publice au fost salvate.",
  changeEmail: "Schimbă emailul",
  newEmail: "Email nou",
  emailUpdated: "Email actualizat",
  changePassword: "Schimbă parola",
  currentPassword: "Parola curentă",
  newPassword: "Parolă nouă",
  passwordChanged: "Parola a fost schimbată",
  temporaryDeactivation: "Dezactivare temporară",
  hideAccountTemporary: "Ascunde contul temporar și deconectează-te.",
  deactivateTemporarily: "Dezactivează temporar",
  language: "Limbă",
  followingFeedError: "Eroare feed Following",
  privacyDashboard: "Confidențialitate / Tablou",
  createTitle: "Creează",
  createSubtitle: "Publică postări text, atașează o imagine sau un videoclip din PC sau deschide un realm nou.",
  realm: "Realm",
  post: "Postare",
  name: "Nume",
  slug: "Slug",
  description: "Descriere",
  createRealm: "Creează realm",
  postTo: "Postează în",
  chooseWherePost: "Alege unde trebuie să apară postarea, de exemplu Home sau Videos.",
  title: "Titlu",
  captionDescription: "Text / Descriere",
  imageOrVideoComputer: "Imagine sau videoclip din calculator",
  chooseAnyImageVideo: "Poți alege orice fișier imagine sau video. Aplicația îl va încadra în postare fără deformare.",
  publishPost: "Publică postarea",
  notificationsTitle: "Notificări",
  analyticsTitle: "Analitice / Creator",
  translateThisText: "Tradu acest text",
  translatedFromOriginal: "Tradus din original",
  startConversation: "Începe conversația",
};
const de: Dictionary = {
  brandSubtitle: "Moderne soziale Plattform",
  feed: "Feed", videos: "Videos", create: "Erstellen", notifications: "Benachrichtigungen", analytics: "Analytik", privacy: "Datenschutz", profile: "Profil", activity: "Aktivität", system: "System", allServicesOnline: "Alle Dienste online", tips: "Tipps", uiConsistency: "Verwende die UI-Komponenten für Konsistenz.", login: "Anmelden", register: "Registrieren", logout: "Abmelden", checkingSession: "Sitzung wird geprüft...", loading: "Lädt...", homeSubtitle: "Ultimatives UI-System aktiviert", online: "ONLINE", openFeed: "Feed öffnen", createPost: "Beitrag erstellen", loginTitle: "Anmeldung", loginSubtitle: "Verwende eine echte Kontositzung mit Cookies und Profilstatus.", email: "E-Mail", password: "Passwort", createAccount: "Konto erstellen", registerSubtitle: "Registriere einen Reelio-Benutzer und beginne zu posten.", username: "Benutzername", min8: "Mindestens 8 Zeichen", feedHomeTitle: "Feed / Start", feedHomeSubtitle: "Öffentliche Beiträge von Reelio-Erstellern durchsuchen.", noPostsYet: "Noch keine Beiträge vorhanden.", videosTitle: "Feed / Videos", videosSubtitle: "Separates Videoraster für Reelio-Clips.", noVideosYet: "Noch keine Videos vorhanden.", comments: "Kommentare", showComments: "Kommentare anzeigen", hideComments: "Kommentare ausblenden", writeComment: "Kommentar schreiben...", postComment: "Kommentar posten", shareThoughts: "Teile deine Gedanken zu diesem Beitrag.", reply: "Antworten", edit: "Bearbeiten", delete: "Löschen", save: "Speichern", cancel: "Abbrechen", translate: "Übersetzung", showOriginal: "Original anzeigen", translating: "Wird übersetzt...", translationUnavailable: "Übersetzung nicht verfügbar", language: "Sprache", title: "Titel", captionDescription: "Beschreibung", imageOrVideoComputer: "Bild oder Video von deinem Computer", publishPost: "Beitrag veröffentlichen", notificationsTitle: "Benachrichtigungen", analyticsTitle: "Analytik / Creator", translatedFromOriginal: "Aus dem Original übersetzt", startConversation: "Konversation starten",
};
const dictionaries: Record<string, Dictionary> = { en, ro, de };

type Ctx = {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
  options: LangOption[];
};

const LanguageContext = createContext<Ctx | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState("en");

  useEffect(() => {
    const saved = typeof window !== "undefined" ? localStorage.getItem("realm.language") : null;
    if (saved) setLanguageState(saved);
  }, []);

  useEffect(() => {
    if (typeof window !== "undefined") {
      localStorage.setItem("realm.language", language);
      document.documentElement.lang = language;
      document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
    }
  }, [language]);

  const value = useMemo<Ctx>(() => ({
    language,
    setLanguage: setLanguageState,
    options: OPTIONS,
    t: (key: string) => dictionaries[language]?.[key] || dictionaries.en[key] || key,
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used inside LanguageProvider");
  return ctx;
}
